---

- hosts: localhost
  roles:
    - { role: common, tags: "common" }
    - { role: git, tags: "git" }
    - { role: zshell, tags: "zshell" }
    - { role: sdks, tags: "sdks" }
    - { role: browsers, tags: "browsers" }
    - { role: docker, tags: "docker" }
    - { role: nodejs, tags: "nodejs" }
    - { role: ruby, tags: "ruby" }
    - { role: atom, tags: "atom" }
    - { role: spotify, tags: "spotify" }
    - { role: neovim, tags: "neovim" }
    - { role: slack, tags: "slack" }
    - { role: jetbrains-toolbox, tags: "jetbrains-toolbox" }
    - { role: rambox, tags: "rambox" }
    - { role: vpn, tags: "vpn" }
    - { role: flycut, tags: "flycut" }
    - { role: stow, tags: "stow" }
    - { role: postman, tags: "postman" }
    - { role: iterm2, tags: "iterm2" }
    - { role: vscode, tags: "vscode" }
    - { role: pass, tags: "pass" }
    # - { role: virtualbox, tags: "virtualbox" }
