# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Shell
    - { role: zshell, tags: "zshell" }
    
    # Programming languages
    - { role: ruby, tags: "ruby" }
    - { role: node, tags: "node" }

    # Editors
    - { role: neovim, tags: "neovim" }
    
    # Dotfiles
    - { role: stow, tags: "stow" }

    # Misc
    - { role: gpg, tags: "gpg" }
    - { role: terraform, tags: "terraform" }
