# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Shell
    - { role: zshell, tags: zshell }
    - { role: terminal, tags: terminal }
    
    # Programming languages
    - { role: ruby, tags: ruby }
    - { role: node, tags: node }

    # Editors
    - { role: neovim, tags: neovim }

    # Window management
    - { role: aerospace, tags: aerospace }
