# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 100
command_timeout = 800

format = """
$directory$git_branch$git_status$git_state$git_metrics$cmd_duration\
$fill\
$ruby$nodejs$bun$terraform$kubernetes$direnv\
$line_break\
$character"""

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style)'
style = "bright-black"
symbol = " "

[git_status]
format = "[( $staged$conflicted$deleted$renamed$modified$typechanged$untracked)( $stashed)( $ahead_behind)]($style)"
style = "cyan"
conflicted = '[=$count](red)'
ahead = '[⇡$count](cyan)'
diverged = '[⇡$ahead_count⇣$behind_count](cyan)'
behind = '[⇣$count](cyan)'
untracked = '[?$count](purple)'
stashed = "[*$count](blue)"
modified = '[!$count](yellow)'
staged = "[+$count](green)"
renamed = "»$count"
deleted = "[✘$count](red)"

[git_state]
format = '[ $state( $progress_current/$progress_total)]($style)'
style = "red"

[git_metrics]
disabled = false
format = ' ([+$added]($added_style)/[-$deleted ]($deleted_style))'

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[git_commit]
tag_symbol = '  '

[hostname]
ssh_symbol = " "
ssh_only = true

[memory_usage]
symbol = "󰍛 "
disabled = true
format = '$symbol[${ram}]($style) '
threshold = 50

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'

[ruby]
symbol = " "
format = '[$symbol($version )]($style)'

[terraform]
symbol = "󱁢 "
format = '[$symbol$workspace]($style) '

[kubernetes]
disabled = false
symbol = "󱃾 "
style = "cyan purple"
format = '[$symbol$context( \($namespace\))]($style) '

[direnv]
disabled = false
allowed_msg = "✓"
loaded_msg = "✓"
unloaded_msg = "✘"
format = '[$symbol]($style)[$loaded]($style)/[$allowed]($style) '

[bun]
symbol = " "
format = '[$symbol($version )]($style)'
style = "cyan"
