#!/bin/bash

# Shims overriding the default binary to run opencode through ai-jail

ai-jail \
  --rw-map=$HOME/.config/opencode \
  --map=$HOME/.gitignore_global \
  --mask=.envrc \
  --status-bar=dark \
  --no-save-config \
  --ssh \
  --gpu \
  --docker \
  --display \
  $(mise bin-paths opencode)/opencode "$@"
