#!/bin/bash

# Shims overriding the default binary to run pi through ai-jail

ai-jail \
  --rw-map=$HOME/.pi \
  --rw-map=$HOME/.pi-lens \
  --map=$HOME/.gitignore_global \
  --mask=.envrc \
  --status-bar=dark \
  --no-save-config \
  --ssh \
  --gpu \
  --docker \
  --display \
  $(mise bin-paths pi)/pi "$@"
