---

- name: Install Node.js
  homebrew:
    name: nodejs
    state: latest

- name: Install latest global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - tslint
    - eslint
