---

- name: Install pyenv
  homebrew:
    name: pyenv
    state: latest

- name: Init pyenv
  shell: pyenv init -

- name: "Install python {{ python_version }}"
  shell: "pyenv install --skip-existing {{ python_version }}"

- name: "Set global version to {{ python_version }}"
  shell: "pyenv global {{ python_version }}"


