---
- name: Add global mise config
  template:
    src: config.toml.j2
    dest: "{{ mise_config_dir }}/config.toml"
    backup: true

- name: Install global mise tools
  shell: "mise install"
  register: mise_result
  changed_when: "mise_result.stderr is search('✓ installed')"
