---

- name: Check if sdkman is installed
  stat:
    path: "{{ user.home }}/.sdkman"
  register: sdk

- name: Installing sdk manager
  shell: curl -s "https://get.sdkman.io" | bash
  args:
    creates: "{{ user.home }}/.sdkman"
    warn: false
  when: not sdk.stat.exists

- name: Update sdkman
  shell: "{{ init_sdkman }} && sdk selfupdate"
  when: sdk.stat.exists

- name: Install sdks
  shell: "{{ init_sdkman }} && sdk install {{ item }}"
  with_items:
    - "{{ sdks }}"
  when: not sdk.stat.exists

- name: Update sdks
  shell: "{{ init_sdkman }} && sdk upgrade {{ item }}"
  with_items:
    - "{{ sdks }}"
  when: sdk.stat.exists
