---

- name: Install Atom
  homebrew_cask:
    name: atom
    state: present

- name: Install Atom packages
  shell: "apm install {{ item }}"
  with_items:
    - language-docker
    - sort-lines
    - file-icons
    - minimap
    - atom-beautify
  changed_when: false
