---

- name: Clone node version manager
  git:
    repo: "{{ github }}creationix/nvm.git"
    dest: "{{ nvm_home }}"
    accept_hostkey: yes
  ignore_errors: yes

- name: Install latest node version
  shell: "{{ init_nvm }} && nvm install node"
  register: nvm_result
  changed_when: "'is already installed' not in nvm_result.stderr"

- name: Install latest global npm packages
  shell: >
    {{ init_nvm }} &&
    npm install -g
    nodemon
    tslint
    typescript
    eslint
    yarn
