---

- name: Check if app exists
  stat:
    path: /Applications/{{ appName }}.app
  register: app_exists

- name: Create tmp dir
  file:
    path: ./tmp
    state: directory
  when: not app_exists.stat.exists

- name: Download app
  get_url:
    url: "{{ downloadURL }}"
    dest: "./tmp/{{ appName }}.zip"
  when: not app_exists.stat.exists

- name: Extract application
  unarchive:
    src: "./tmp/{{ appName }}.zip"
    dest: /Applications/{{ appName }}.app
  when: not app_exists.stat.exists

- name: Delete tmp dir
  file:
    path: ./tmp
    state: absent
  when: not app_exists.stat.exists
