---

- name: Install Sublime Text
  homebrew_cask:
    name: sublime-text
    state: present

- name: Create required Sublime directories
  file:
    path: "{{ sublime_config_dir }}/{{ item }}"
    state: directory
  with_items:
    - Installed Packages
    - Packages

- name: Install Sublime Package Control
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: "{{ sublime_config_dir }}/Installed Packages/Package Control.sublime-package"
