---

- name: Perform upgrade
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install common tools
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - npm
    - go
    - python3
    - coreutils
    - findutils
    - gnupg
    - grep
    - openssh
    - wget

- name: Install gnu-sed
  homebrew:
    name: gnu-sed
    state: latest
    install_options: with-default-names
