---

- name: Perform upgrade
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install common tools
  homebrew:
    name:
      - python3
      - coreutils
      - findutils
      - gnupg
      - grep
      - wget
      - bat
      - prettyping
      - ncdu
      - tldr
      - direnv
      - todolist
    state: latest

- name: Install gnu-sed
  homebrew:
    name: gnu-sed
    state: latest
    install_options: with-default-names
