---

- name: Perform upgrade
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install common tools
  homebrew:
    name:
      - coreutils
      - findutils
      - grep
      - wget
      - bat
      - prettyping
      - ncdu
      - tldr
      - direnv
      - gnu-sed
    state: latest
