---

- name: Install Docker for mac
  include: group_vars/tasks/dmg_install.yml appName=Docker dmgURL=https://download.docker.com/mac/edge/Docker.dmg

- name: Install docker machine
  homebrew:
    name: docker-machine
    state: latest
