---

- name: Install Docker for mac
  import_tasks: group_vars/tasks/dmg_install.yml appName=Docker downloadURL=https://download.docker.com/mac/stable/Docker.dmg

- name: Install docker machine cli completion
  homebrew:
    name: docker-machine-completion
    state: latest
