---

- name: Install docker
  homebrew_cask:
    name: docker
    state: present

- name: Install docker ecr credentials helper
  homebrew:
    name: docker-credential-helper-ecr
    state: latest

- name: Create .docker directory
  file:
    path: "{{ user.home }}/.docker"
    state: directory

- name: Add docker config for cred helper
  template:
    src: config.json.j2
    dest: "{{ user.home }}/.docker/config.json"
    force: no
