---

- name: Install docker
  homebrew_cask:
    name: docker
    state: present

- name: Install docker ecr credentials helper
  homebrew:
    name: docker-credential-helper-ecr
    state: latest

- name: Tap lazydocker
  homebrew_tap:
    name: jesseduffield/lazydocker
  
- name: Install lazydocker
  homebrew:
    name: lazydocker
    state: latest
