---

- name: Clone nvchad
  git:
    repo: "{{ github }}NvChad/starter"
    dest: "{{ user.home }}/.config/nvim"
    accept_hostkey: yes
    force: yes

- name: Add chadrc.lua
  template:
    src: chadrc.lua.j2
    dest: "{{ nvchad_dir }}/lua/chadrc.lua"

- name: Add colorcolumn option
  lineinfile:
    path: "{{ nvchad_dir }}/init.lua"
    line: vim.opt.colorcolumn = "120"
    state: present
