---

- name: Clone nvchad
  git:
    repo: "{{ github }}NvChad/NvChad"
    dest: "{{ user.home }}/.config/nvim"
    accept_hostkey: yes

- name: Add chadrc.lua
  template:
    src: chadrc.lua.j2
    dest: "{{ nvchad_custom_dir }}/chadrc.lua"

- name: Add init.lua
  template:
    src: init.lua.j2
    dest: "{{ nvchad_custom_dir }}/init.lua"
