---

- name: Add public keys
  shell: |
    gpg \
    --keyserver hkp://keys.gnupg.net \
    --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    
- name: Installing ruby version manager
  shell: "curl -sSL https://get.rvm.io | bash -s stable --ignore-dotfiles"
  args:
    creates: "{{ rvm_home }}"
    warn: false

- name: Install ruby
  shell: "{{ init_rvm }} && rvm install {{ ruby_version }}"

- name: Generate ruby docs
  shell: "{{ init_rvm }} && rvm docs generate-ri"

- name: Install ruby gems
  shell: "{{ init_rvm }} && gem install {{ item }}"
  with_items:
    - fastri
    - solargraph
    - rdoc
    - rubocop
