---

- name: Add public keys
  shell: |
    gpg \
    --keyserver hkp://keys.gnupg.net \
    --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

- name: Installing ruby version manager
  shell: "curl -sSL https://get.rvm.io | bash -s stable --ruby --ignore-dotfiles"
  args:
    creates: "{{ user.home }}/.rvm"
    warn: false

- name: Install ruby gems
  gem:
    name: "{{ item }}"
    state: latest
  with_items:
    - fastri
    - rcodetools
    - rdoc
    - rubocop
